version: '2'

services:
  node:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
  web-dev:
    build:
      context: .
      dockerfile: ./development/Dockerfile
    container_name: next-playground
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "4200:4200"
